apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-[student-name]
  namespace: [student-name]
spec:
  storageClassName: database
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
