apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: [student-name]
spec:
  hard:
    pods: 5
    "requests.cpu": "2"
    "requests.memory": 1024Mi
    "limits.cpu": "4"
    "limits.memory": 2048Mi
