apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: [student-name]
  labels:
    type: local
spec:
  storageClassName: document
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db/[student-name]"
