apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: [student-name]
spec:
  storageClassName: document
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi