apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  spring.datasource.password: cGFzc3dvcmQ=
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql
  namespace: [replace-this-with-your-namespace]
